export default [
    {
        id: 1,
        name: "YAYA MOT",
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img: "https://i.ebayimg.com/images/g/VNoAAOSwUlJhCQP6/s-l1200.webp",
        experience: "6 years",
        location: "NCR",
        openSpots: 0,
    },
    {
        id: 2,
        name: "YAYA BOG",
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img: "https://trishatruly.files.wordpress.com/2008/10/french61.jpg",
        experience: "5 years",
        location: "Visayas",
        openSpots: 0,
    },
    {
        id: 3,
        name: "YAYA MOT",
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img: "https://down-ph.img.susercontent.com/file/bb574f1b2b5758d05c07c309caf16f51",
        experience: "4 years",
        location: "NCR",
        openSpots: 0,
    },
    {
        id: 4,
        name: "YAYA KAP",
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img: "https://i.ytimg.com/vi/-L6GvHTnNqw/maxresdefault.jpg",
        experience: "3 years",
        location: "Mindanao",
        openSpots: 1,
    },
    {
        id: 4,
        name: "YAYA TESTING",
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        img: "https://i.ytimg.com/vi/-L6GvHTnNqw/maxresdefault.jpg",
        experience: "3 years",
        location: "Mindanao",
        openSpots: 1,
    },
]